//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.QuyTrinh.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.QuyTrinh.Core.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be null.
        /// </summary>
        internal static string Email_EN {
            get {
                return ResourceManager.GetString("Email_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không được để trống.
        /// </summary>
        internal static string Email_VN {
            get {
                return ResourceManager.GetString("Email_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not in the correct format.
        /// </summary>
        internal static string EmailValid_EN {
            get {
                return ResourceManager.GetString("EmailValid_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng.
        /// </summary>
        internal static string EmailValid_VN {
            get {
                return ResourceManager.GetString("EmailValid_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName cannot be null.
        /// </summary>
        internal static string FullName_EN {
            get {
                return ResourceManager.GetString("FullName_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng không được để trống.
        /// </summary>
        internal static string FullName_VN {
            get {
                return ResourceManager.GetString("FullName_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role cannot be null.
        /// </summary>
        internal static string Role_EN {
            get {
                return ResourceManager.GetString("Role_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vai trò người dùng không được để trống.
        /// </summary>
        internal static string Role_VN {
            get {
                return ResourceManager.GetString("Role_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status cannot be null.
        /// </summary>
        internal static string Status_EN {
            get {
                return ResourceManager.GetString("Status_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái người dùng không được để trống.
        /// </summary>
        internal static string Status_VN {
            get {
                return ResourceManager.GetString("Status_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User code cannot be null.
        /// </summary>
        internal static string UserCode_EN {
            get {
                return ResourceManager.GetString("UserCode_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã người dùng không được để trống.
        /// </summary>
        internal static string UserCode_VN {
            get {
                return ResourceManager.GetString("UserCode_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User code already exists in the system.
        /// </summary>
        internal static string UserCodeExist_EN {
            get {
                return ResourceManager.GetString("UserCodeExist_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã người dùng đã tồn tại.
        /// </summary>
        internal static string UserCodeExist_VN {
            get {
                return ResourceManager.GetString("UserCodeExist_VN", resourceCulture);
            }
        }
    }
}
